# Shell variables
# Generated by 'wal'
wallpaper='/home/tom/Bilder/Hintergründe/wallpaper-main/wallhaven-l8q85r.jpg'

# Special
background='#0f1417'
foreground='#dfe3e7'
cursor='#90cef4'

# Colors
color0='#0f1417'
color1='#90cef4'
color2='#b5c9d7'
color3='#cac1e9'
color4='#c4e7ff'
color5='#d1e5f4'
color6='#e7deff'
color7='#dfe3e7'

color8='#0f1417'
color9='#00344a'
color10='#20333e'
color11='#322c4c'
color12='#001e2c'
color13='#0a1e28'
color14='#1d1736'
color15='#dfe3e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"