# Shell variables
# Generated by 'wal'
wallpaper='/home/tom/Bilder/Hintergründe/wallpaper-main/wallhaven-l8q85r.jpg'

# Special
background='#0e1514'
foreground='#dde4e3'
cursor='#80d4d5'

# Colors
color0='#0e1514'
color1='#80d4d5'
color2='#b0cccb'
color3='#b3c8e9'
color4='#9cf1f1'
color5='#cce8e7'
color6='#d3e3ff'
color7='#dde4e3'

color8='#0e1514'
color9='#003737'
color10='#1b3435'
color11='#1d314b'
color12='#002020'
color13='#041f20'
color14='#051c35'
color15='#dde4e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"