# Shell variables
# Generated by 'wal'
wallpaper='/home/tom/Bilder/Hintergründe/wallpaper-main/wallhaven-l8q85r.jpg'

# Special
background='{{colors.surface.default.hex}}'
foreground='{{colors.on_surface.default.hex}}'
cursor='{{colors.primary_fixed_dim.default.hex}}'

# Colors
color0='{{colors.surface.default.hex}}'
color1='{{colors.primary.default.hex}}'
color2='{{colors.secondary.default.hex}}'
color3='{{colors.tertiary.default.hex}}'
color4='{{colors.primary_fixed.default.hex}}'
color5='{{colors.secondary_fixed.default.hex}}'
color6='{{colors.tertiary_fixed.default.hex}}'
color7='{{colors.on_surface.default.hex}}'

color8='{{colors.surface_dim.default.hex}}'
color9='{{colors.on_primary.default.hex}}'
color10='{{colors.on_secondary.default.hex}}'
color11='{{colors.on_tertiary.default.hex}}'
color12='{{colors.on_primary_fixed.default.hex}}'
color13='{{colors.on_secondary_fixed.default.hex}}'
color14='{{colors.on_tertiary_fixed.default.hex}}'
color15='{{colors.on_surface.default.hex}}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"