# acpi
# Autogenerated from man page /usr/share/man/man1/acpi.1.gz
complete -c acpi -s b -l battery -d 'show battery information'
complete -c acpi -s a -l ac-adapter -d 'show ac adapter information'
complete -c acpi -s t -l thermal -d 'show thermal information'
complete -c acpi -s c -l cooling -d 'show cooling device information'
complete -c acpi -s V -l everything -d 'show every device, overrides above options'
complete -c acpi -s s -l show-empty -d 'show non-operational devices'
complete -c acpi -s i -l details -d 'show additional details if available:'
complete -c acpi -s f -l fahrenheit -d 'use fahrenheit as the temperature unit instead of default celsius'
complete -c acpi -s k -l kelvin -d 'use kelvin as the temperature unit instead of default celsius'
complete -c acpi -s p -l proc -d 'use the old /proc interface, default is the new /sys one'
complete -c acpi -s d -l directory -d 'path to ACPI info (either /proc/acpi or /sys/class)'
complete -c acpi -s h -l help -d 'display help and exit'

