# add-apt-key
# Autogenerated from man page /usr/share/man/man8/add-apt-key.8.gz
complete -c add-apt-key -s h -l help -d 'Show online help (usage)'
complete -c add-apt-key -s v -l verbose -d 'verbose mode will show each command before it is executed'
complete -c add-apt-key -s k -l keyserver -d 'Select a specific keyserver to use'

