# add-apt-repository
# Autogenerated from man page /usr/share/man/man1/add-apt-repository.1.gz
complete -c add-apt-repository -s h -l help -d 'Show help message and exit'
complete -c add-apt-repository -s y -l yes -d 'Assume yes to all queries'

