# apt-add-repository
# Autogenerated from man page /usr/share/man/man1/apt-add-repository.1.gz
complete -c apt-add-repository -s h -l help -d 'Show help message and exit'
complete -c apt-add-repository -s y -l yes -d 'Assume yes to all queries'

