# apt-clone
# Autogenerated from man page /usr/share/man/man8/apt-clone.8.gz
complete -c apt-clone -s h -l help -d 'show help message for apt-clone'
complete -c apt-clone -l debug -d 'enable debug output '

