# aptitude-run-state-bundle
# Autogenerated from man page /usr/share/man/man1/aptitude-run-state-bundle.1.gz
complete -c aptitude-run-state-bundle -l append-args -d 'Place the options that give the location of the state bundle at the end of th…'
complete -c aptitude-run-state-bundle -l help -d 'Display a brief usage summary'
complete -c aptitude-run-state-bundle -l prepend-args -d 'Place the options that give the location of the state bundle at the beginning…'
complete -c aptitude-run-state-bundle -l no-clean -d 'Do not remove the unpacked state directory after running aptitude'
complete -c aptitude-run-state-bundle -l really-clean -d 'Delete the state directory after running aptitude, even if --no-clean or --st…'
complete -c aptitude-run-state-bundle -l statedir -d 'Instead of treating the input file as a state bundle, treat it as an unpacked…'
complete -c aptitude-run-state-bundle -l unpack -d 'Unpack the input file to a temporary directory, but don\\*(Aqt actually run ap…'

