# arcstat
# Autogenerated from man page /usr/share/man/man8/arcstat.8.gz
complete -c arcstat -s a -d 'Print all possible stats'
complete -c arcstat -s f -d 'Display only specific fields.  See DESCRIPTION for supported statistics'
complete -c arcstat -s h -d 'Display help message'
complete -c arcstat -s o -d 'Report statistics to a file instead of the standard output'
complete -c arcstat -s p -d 'Disable auto-scaling of numerical fields (for raw, machine-parsable values)'
complete -c arcstat -s s -d 'Display data with a specified separator (default: 2 spaces)'
complete -c arcstat -s x -d 'Print extended stats same as Fl f Sy time , Ns Sy mfu , Ns Sy mru , Ns Sy mfu…'
complete -c arcstat -s v -d 'Show field headers and definitions El OPERANDS The following operands are sup…'

