# btrfsck
# Autogenerated from man page /usr/share/man/man8/btrfsck.8.gz
complete -c btrfsck -s b -l backup
complete -c btrfsck -l super -d 'if some of the superblocks are damaged'
complete -c btrfsck -l check-data-csum
complete -c btrfsck -l chunk-root
complete -c btrfsck -s E -l subvol-extents
complete -c btrfsck -s p -l progress
complete -c btrfsck -s Q -l qgroup-report
complete -c btrfsck -s r -l tree-root
complete -c btrfsck -l readonly
complete -c btrfsck -s s
complete -c btrfsck -l clear-space-cache
complete -c btrfsck -l clear-ino-cache
complete -c btrfsck -l repair
complete -c btrfsck -l force -d 'to give users a chance to think twice before running repair, the warnings in …'
complete -c btrfsck -l init-csum-tree
complete -c btrfsck -l init-extent-tree
complete -c btrfsck -l mode

