# cinnamon-settings
# Autogenerated from man page /usr/share/man/man1/cinnamon-settings.1.gz
complete -c cinnamon-settings -s h -l help -d 'Print a help text describing the supported command-line options, and then exit'
complete -c cinnamon-settings -s s -l sort -d 'Specific to the \'download\' tab (see below) for applets, desklets, extensions …'
complete -c cinnamon-settings -s t -l tab -d 'Select the tab to open in the settings'

