# cinnamon-session-quit
# Autogenerated from man page /usr/share/man/man1/cinnamon-session-quit.1.gz
complete -c cinnamon-session-quit -l logout -d 'Prompt the user to confirm logout.  This is the default behavior'
complete -c cinnamon-session-quit -l power-off -d 'Prompt the user to confirm system power off'
complete -c cinnamon-session-quit -l reboot -d 'Prompt the user to confirm system reboot'
complete -c cinnamon-session-quit -l force -d 'Ignore any inhibitors'
complete -c cinnamon-session-quit -l no-prompt -d 'End the session without user interaction.  This only works with --logout'

