# cinnamon-session
# Autogenerated from man page /usr/share/man/man1/cinnamon-session.1.gz
complete -c cinnamon-session -l autostart -d 'Start all applications defined in DIR, instead of starting the applications d…'
complete -c cinnamon-session -l session -d 'Use the applications defined in SESSION. session.  If not specified, gnome'
complete -c cinnamon-session -l failsafe -d 'Run in fail-safe mode.  User-specified applications will not be started'
complete -c cinnamon-session -l debug -d 'Enable debugging code'
complete -c cinnamon-session -l whale -d 'Show the fail whale in a dialog for debugging it'

