# cinnamon2d
# Autogenerated from man page /usr/share/man/man1/cinnamon2d.1.gz
complete -c cinnamon2d -l replace -d 'Replace the running window manager . br'
complete -c cinnamon2d -l sm-disable -d 'Disable connection to the session manager . br'
complete -c cinnamon2d -l sm-client-id -d 'Specify session management ID . br'
complete -c cinnamon2d -l sm-save-file -d 'Initialize session from savefile . br'
complete -c cinnamon2d -l screen -d 'X screen to use . br'
complete -c cinnamon2d -s d -l display -d 'X display to use . br'
complete -c cinnamon2d -l sync -d 'Make X calls synchronous . br'
complete -c cinnamon2d -l version -d 'Print version and exit . br'
complete -c cinnamon2d -l help -d 'Display help and exit'

