# cinnamon
# Autogenerated from man page /usr/share/man/man1/cinnamon.1.gz
complete -c cinnamon -l replace -d 'Replace the running window manager . br'
complete -c cinnamon -l sm-disable -d 'Disable connection to the session manager . br'
complete -c cinnamon -l sm-client-id -d 'Specify session management ID . br'
complete -c cinnamon -l sm-save-file -d 'Initialize session from savefile . br'
complete -c cinnamon -l screen -d 'X screen to use . br'
complete -c cinnamon -s d -l display -d 'X display to use . br'
complete -c cinnamon -l sync -d 'Make X calls synchronous . br'
complete -c cinnamon -l version -d 'Print version and exit . br'
complete -c cinnamon -l help -d 'Display help and exit'

