# dpkg-repack
# Autogenerated from man page /usr/share/man/man1/dpkg-repack.1.gz
complete -c dpkg-repack -l root -d 'Take package from filesystem rooted on dir'
complete -c dpkg-repack -l arch -d 'Make the package be for a specific architecture'
complete -c dpkg-repack -s d -l deb-option -d 'Pass option as build argument to dpkg-deb'
complete -c dpkg-repack -l generate -d 'Generate a temporary directory suitable for building a package from, but do n…'
complete -c dpkg-repack -l tag -d 'Specify a comma-separated list of things to tag in the package as having been…'

