# editdiff
# Autogenerated from man page /usr/share/man/man1/editdiff.1.gz
complete -c editdiff -l help -d 'Display a short usage message'
complete -c editdiff -l version -d 'Display the version number of rediff'

