# exonpairs
# Autogenerated from man page /usr/share/man/man1/exonpairs.1.gz
complete -c exonpairs -o min-intron -d 'minimum Intron length [30]'
complete -c exonpairs -o max-intron -d 'maximum Intron length [10000]'
complete -c exonpairs -o einit-length -d 'minimum Einit length in bp [10]'
complete -c exonpairs -o eterm-length -d 'minimum Eterm length in bp [10]'
complete -c exonpairs -o exon-length -d 'minimum Exon length in bp [30] '
complete -c exonpairs -o einit-score -d 'minimum Einit score in bits [-5]'
complete -c exonpairs -o eterm-score -d 'minimum Eterm score in bits [-5]'
complete -c exonpairs -o exon-score -d 'minimum Exon score in bits [-5]'
complete -c exonpairs -o pair-score -d 'minimum pair score (exon-intron-exon) [10]'
complete -c exonpairs -o flank-length -d 'length of flanking sequence per exon [20]'
complete -c exonpairs -o intron-score
complete -c exonpairs -o lcmask -d 'treat lowercase as N'

