# fathom
# Autogenerated from man page /usr/share/man/man1/fathom.1.gz
complete -c fathom -o help -d 'report useful information'
complete -c fathom -o validate
complete -c fathom -o gene-stats -o errors-ok -o nucleotide -o dinucleotide
complete -c fathom -o categorize
complete -c fathom -o export -o plus
complete -c fathom -o extract -o length -o offset
complete -c fathom -o exon-intron
complete -c fathom -o split -o training -o GC -o repeat
complete -c fathom -o ace-format -o dna -o extra
complete -c fathom -o compare-genes
complete -c fathom -o score-genes
complete -c fathom -o filter-genes -o min-score -o min-length

