# forge
# Autogenerated from man page /usr/share/man/man1/forge.1.gz
complete -c forge -o pseudocount -d '[1]   (absolute number for all models) . HP -pseudoCoding <float> [0. 0] (eg'
complete -c forge -o pseudoInter -d '[0. 0]'
complete -c forge -o min-counts -d '[0] . HP -lcmask [-fragmentN]'
complete -c forge -o utr5-length -d '[50]'
complete -c forge -o utr5-offset -d '[10]'
complete -c forge -o utr3-length -d '[50]'
complete -c forge -o utr3-offset -d '[10]'
complete -c forge -o explicit -d '[250]'
complete -c forge -o min-intron -d '[30]'
complete -c forge -o help
complete -c forge -o verbose
complete -c forge -o pseudoCoding
complete -c forge -o pseudoIntron
complete -c forge -o lcmask
complete -c forge -o boost -d '(file of ID <int>)'

