# hexchat
# Autogenerated from man page /usr/share/man/man1/hexchat.1.gz
complete -c hexchat -s h -l help -d 'Show help options'
complete -c hexchat -l help-all -d 'Show all help options'
complete -c hexchat -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c hexchat -s a -l no-auto -d 'Don\'t auto connect to servers'
complete -c hexchat -s d -l cfgdir -d 'Use a different config directory'
complete -c hexchat -s n -l no-plugins -d 'Don\'t auto load any plugins'
complete -c hexchat -s p -l plugindir -d 'Show plugin auto-load directory'
complete -c hexchat -s u -l configdir -d 'Show user config directory'
complete -c hexchat -l url -d 'Open an irc://server:port/channel?key URL'
complete -c hexchat -s c -l command -d 'Execute command:'
complete -c hexchat -s e -l existing -d 'Open URL or execute command in an existing HexChat'
complete -c hexchat -l minimize -d 'Begin minimized.  Level 0=Normal 1=Iconified 2=Tray'
complete -c hexchat -s v -l version -d 'Show version information'
complete -c hexchat -l display -d 'X display to use'

