# html2text
# Autogenerated from man page /usr/share/man/man1/html2text.1.gz
complete -c html2text -o nometa -d 'By default, Debian version of html2text use \'meta http-equiv\' tag for input r…'
complete -c html2text -o ascii -d 'By default, when -nometa is supplied,  html2text uses  UTF-8 for the output'
complete -c html2text -o utf8 -d 'By default, when -nometa is supplied,  html2text uses  ISO 8859-1 for the inp…'
complete -c html2text -o check -d 'This option is for diagnostic purposes: The HTML document is only parsed and …'
complete -c html2text -o debug-parser -d 'Let  html2text report on the tokens being shifted, rules being applied, etc'
complete -c html2text -o debug-scanner -d 'Let  html2text report on each lexical token scanned, while scanning the HTML …'
complete -c html2text -o help -d 'Print command line summary and exit'
complete -c html2text -o nobs -d 'By default, original  html2text renders underlined letters with sequences lik…'
complete -c html2text -s o -d 'Write the output to  output-file instead of standard output'
complete -c html2text -o rcfile -d 'Attempt to read the file specified in  path as RC file'
complete -c html2text -o style -d 'Style  pretty changes some of the default values of the formatting parameters…'
complete -c html2text -o unparse -d 'This option is for diagnostic purposes: Instead of formatting the parsed docu…'
complete -c html2text -o version -d 'Print program version and exit'
complete -c html2text -o width -d 'By default, html2text formats the HTML documents for a screen width of 79 cha…'

