# ideviceinstaller
# Autogenerated from man page /usr/share/man/man1/ideviceinstaller.1.gz
complete -c ideviceinstaller -s d -l debug -d 'enable communication debugging'
complete -c ideviceinstaller -s u -l udid -d 'target specific device by its 40-digit device UDID'
complete -c ideviceinstaller -s h -l help -d 'prints usage information  . SS Commands:'
complete -c ideviceinstaller -s l -l list-apps -d 'list apps installed on the device. RS  Additional options:'
complete -c ideviceinstaller -s o -d 'list user apps only (apps installed by the user)  This is the default'
complete -c ideviceinstaller -s i -l install -d 'install app from a package file specified by ARCHIVE.  ARCHIVE can also be a '
complete -c ideviceinstaller -s U -l uninstall -d 'uninstall app specified by APPID'
complete -c ideviceinstaller -s g -l upgrade -d 'upgrade app from a package file specified by ARCHIVE'
complete -c ideviceinstaller -s r -l restore -d 'restore archived app specified by APPID'
complete -c ideviceinstaller -s L -l list-archives -d 'list archived applications on the device. RS  Additional options:'
complete -c ideviceinstaller -s a -l archive -d 'archive app specified by APPID. RS  Additional options:'
complete -c ideviceinstaller -s R -l remove-archive -d 'remove app archive specified by APPID'

