# ifuse
# Autogenerated from man page /usr/share/man/man1/ifuse.1.gz
complete -c ifuse -s o -d 'mount options'
complete -c ifuse -s u -l uuid -d 'mount specific device by its 40-digit device UUID'
complete -c ifuse -s h -l help -d 'prints usage information'
complete -c ifuse -s V -l version -d 'print version'
complete -c ifuse -s d -l debug -d 'enable libimobiledevice communication debugging'
complete -c ifuse -l documents -d 'mount \'Documents\' folder of app identified by APPID'
complete -c ifuse -l container -d 'mount sandbox root of an app identified by APPID'
complete -c ifuse -l root -d 'mount root file system (jailbroken device required)'

