# install-menu
# Autogenerated from man page /usr/share/man/man1/install-menu.1.gz
complete -c install-menu -s h -l help -d 'Show the help message and exit'
complete -c install-menu -l remove -d 'Remove the menu files instead of generating them'
complete -c install-menu -s v -l verbose -d 'Output messages about what the program is doing'

