# install-docs
# Autogenerated from man page /usr/share/man/man8/install-docs.8.gz
complete -c install-docs -s v -l verbose -d 'Operate verbosely'
complete -c install-docs -s d -l debug -d 'Print some debugging information'
complete -c install-docs -l no-update-menus -d 'Inhibit running dwww-build-menu\\|(8), and dhelp_parse\\|(8)'

