# isohybrid
# Autogenerated from man page /usr/share/man/man1/isohybrid.pl.1.gz
complete -c isohybrid -o entry -d 'Specify partition entry number (1-4)'
complete -c isohybrid -o offset -d 'Specify partition offset (default 0)'
complete -c isohybrid -o type -d 'Specify partition type (default 0x17)'
complete -c isohybrid -o id -d 'Specify MBR ID (default random)'
complete -c isohybrid -o forcehd0 -d 'Always assume we are loaded as disk ID 0'
complete -c isohybrid -o ctrlhd0 -d 'Assume disk ID 0 if the Ctrl key is pressed'
complete -c isohybrid -o partok -d 'Allow booting from within a partition'

