# jjs
# Autogenerated from man page /usr/share/man/man1/jjs.1.gz
complete -c jjs -o cp -d 'Specifies the path to the supporting class files To set multiple paths, the o…'
complete -c jjs -o Dname -d 'Sets a system property to be passed to the script by assigning a value to a p…'
complete -c jjs -o 'doe
.br
--dump-on-error' -d 'Provides a full stack trace when an error occurs'
complete -c jjs -o 'fv
.br
--fullversion' -d 'Prints the full Nashorn version string'
complete -c jjs -o fx -d 'Launches the script as a JavaFX application'
complete -c jjs -o 'h
.br
-help' -d 'Prints the list of options and their descriptions'
complete -c jjs -l language -d 'Specifies the ECMAScript language version.  The default version is ES5'
complete -c jjs -o 'ot
.br
--optimistic-types' -d 'Enables or disables optimistic type assumptions with deoptimizing recompilati…'
complete -c jjs -o scripting -d 'Enables shell scripting features'
complete -c jjs -o strict -d 'Enables strict mode, which enforces stronger adherence to the standard (ECMAS…'
complete -c jjs -s t -d 'Sets the specified time zone for script execution'
complete -c jjs -o 'v
.br
-version' -d 'Prints the Nashorn version string'
complete -c jjs -o classpath
complete -c jjs -o doe
complete -c jjs -l dump-on-error
complete -c jjs -o fv
complete -c jjs -l fullversion
complete -c jjs -s h
complete -c jjs -o help
complete -c jjs -o ot
complete -c jjs -l optimistic-types
complete -c jjs -o timezone
complete -c jjs -s v
complete -c jjs -o version

