# JxrDecApp
# Autogenerated from man page /usr/share/man/man1/JxrDecApp.1.gz
complete -c JxrDecApp -s i -d 'Input JPEG XR/HD Photo file name . PP'
complete -c JxrDecApp -s o -d 'Output image file name bmp: <=8bpc, BGR pnm: >=8bpc, RGB tif: >=8bpc, RGB…'
complete -c JxrDecApp -s c -d 'Specifies the uncompressed output format 0: 24bppBGR 1: 1bppBlackWhite 2: …'
complete -c JxrDecApp -s r -d 'Specifies the rectangle for region decode . PP'
complete -c JxrDecApp -s T -d 'Reduced resolution (mipmap) decode 0: Full resolution (default) 1: 1/2 res …'
complete -c JxrDecApp -s O -d '0: No transformation (default) 1: Flip vertically 2: Flip horizontally 3: …'
complete -c JxrDecApp -s s -d 'Used for compressed domain transcoding 0: All subbands included (default) 1…'
complete -c JxrDecApp -s a -d '0: Decode without alpha channel 1: Decode only alpha channel 2: Decode imag…'
complete -c JxrDecApp -s p -d 'Post processing filter strength 0: None (default) 1: Light 2: Medium 3: S…'
complete -c JxrDecApp -s C -d 'Suppress overlapping boundary macro blocks (Used for compressed domain tile …'
complete -c JxrDecApp -s t -d 'Display timing information . PP'
complete -c JxrDecApp -s v -d 'Display verbose decoder information'

