# JxrEncApp
# Autogenerated from man page /usr/share/man/man1/JxrEncApp.1.gz
complete -c JxrEncApp -s i -d 'Input image file name bmp: <=8bpc, BGR pnm: >=8bpc, RGB tif: >=8bpc, RGB …'
complete -c JxrEncApp -s o -d 'Output JPEG XR file name . PP'
complete -c JxrEncApp -s q -d '[0. 0 - 1. 0) Default = 1. 0, lossless'
complete -c JxrEncApp -s c -d 'Required to define uncompressed source pixel format 0: 24bppBGR 1: 1bppBlac…'
complete -c JxrEncApp -s d -d '0: Y-only 1: YCoCg 4:2:0 2: YCoCg 4:2:2 3: YCoCg 4:4:4 (default) P (if no…'
complete -c JxrEncApp -s l -d '0: No overlapping 1: One level overlapping (default) 2: Two level overlappi…'
complete -c JxrEncApp -s f -d 'Turn off frequency order bit stream (to spatial) . PP'
complete -c JxrEncApp -s p -d 'Turn off progressive mode (to sequential) . PP'
complete -c JxrEncApp -s t -d 'Display timing information . PP'
complete -c JxrEncApp -s v -d 'Display verbose encoder information . PP'
complete -c JxrEncApp -s V -d 'Macro block columns per tile  . PP'
complete -c JxrEncApp -s H -d 'Macro block rows per tile . PP'
complete -c JxrEncApp -s U -d 'Vertical & horizontal tile count for uniform tiling . PP'
complete -c JxrEncApp -s b -d 'Applies to 1bpp black/white images 0: 0 = black (default) 1: 0 = white '
complete -c JxrEncApp -s a -d 'Required for any pixel format with an alpha channel 2: Planar alpha (default…'
complete -c JxrEncApp -s Q -d '[1 - 255] Default = 1, lossless . PP'
complete -c JxrEncApp -s F -d '[0 - 15]  0: no trimming (default) 15: trim all . PP'
complete -c JxrEncApp -s s -d '0: All subbands included (default) 1: Skip flexbits 2: Skip highpass 3: Sk…'

