# lintian-annotate-hints
# Autogenerated from man page /usr/share/man/man1/lintian-annotate-hints.1.gz
complete -c lintian-annotate-hints -s a -l annotate -d 'Read from standard input or any files specified on the command line and searc…'
complete -c lintian-annotate-hints -s h -l help -d 'Display usage information and exit'
complete -c lintian-annotate-hints -l include-dir -d 'Use dir as an additional \\*(L"Lintian root\\*(R"'
complete -c lintian-annotate-hints -l profile -d 'Use the severities from the vendor profile prof when displaying tags'

