# lintian-explain-tags
# Autogenerated from man page /usr/share/man/man1/lintian-explain-tags.1.gz
complete -c lintian-explain-tags -s l -l list-tags -d 'List all tags Lintian knows about in sorted order'
complete -c lintian-explain-tags -s h -l help -d 'Display usage information and exit'
complete -c lintian-explain-tags -l include-dir -d 'Use dir as an additional \\*(L"Lintian root\\*(R"'
complete -c lintian-explain-tags -l profile -d 'Use the severities from the vendor profile prof when displaying tags'
complete -c lintian-explain-tags -s t -l tag -l tags -d 'This option has no effect.  It exists for historical reasons'

