# locate
# Autogenerated from man page /usr/share/man/man1/locate.1.gz
complete -c locate -s A -l all -d 'Ignored for compatibility with  mlocate (1)'
complete -c locate -s b -l basename -d 'Match only against the file name portion of the path name, ie'
complete -c locate -s c -l count -d 'Do not print each match'
complete -c locate -s d -l database -d 'Find matches in the given database, instead of /var/lib/plocate/plocate. db'
complete -c locate -s e -l existing -d 'Print only entries that refer to files existing at the time  locate is run'
complete -c locate -s i -l ignore-case -d 'Do a case-insensitive match as given by the current locale (default is case-s…'
complete -c locate -s p -l ignore-spaces -d 'Ignore punctuation and spaces when matching patterns'
complete -c locate -s l -l limit -d 'Stop searching after  LIMIT matches have been found'
complete -c locate -s N -l literal -d 'Print entry names without quoting'
complete -c locate -s 0 -l null -d 'Instead of writing a newline after every match, write a NUL (ASCII 0)'
complete -c locate -s r -l regexp -d 'Patterns are taken to be POSIX basic regular expressions'
complete -c locate -l regex -d 'Like --regexp, but patterns are instead taken to be POSIX  extended regular e…'
complete -c locate -s w -l wholename -d 'Match against the entire path name'
complete -c locate -l help -d 'Print out usage information, then exit successfully'
complete -c locate -l version -d 'Print out version information, then exit successfully'

