# metacity
# Autogenerated from man page /usr/share/man/man1/metacity.1.gz
complete -c metacity -l display -d 'Connect to X display DISPLAY'
complete -c metacity -l replace -d 'a window manager which is running is replaced by metacity'
complete -c metacity -l sm-client-id -d 'Specify a session management ID'
complete -c metacity -l sm-disable -d 'Disable the session management'
complete -c metacity -l sm-save-file -d 'Load a session from FILENAME'
complete -c metacity -l sync -d 'Make X calls synchronous'
complete -c metacity -l composite -d 'Turn compositing on'
complete -c metacity -l no-composite -d 'Turn compositing off'
complete -c metacity -l no-force-fullscreen -d 'Don\'t make fullscreen windows that are maximized and have no decorations'
complete -c metacity -l version -d 'Print the version number'
complete -c metacity -s '?' -l help -d 'Show summary of options'

