# mkdiskimage
# Autogenerated from man page /usr/share/man/man1/mkdiskimage.1.gz
complete -c mkdiskimage -s 4 -d 'Use the fourth partition table entry.  This is the standard for ZIP-disks'
complete -c mkdiskimage -s F -d 'Format the partition using a FAT32 file system'
complete -c mkdiskimage -s M -d 'The argument cyl is given in Megabytes'
complete -c mkdiskimage -s d -d 'Add a DOSEMU header'
complete -c mkdiskimage -s i -d 'Specify the MBR identity field as id'
complete -c mkdiskimage -s o -d 'Print to stdout the file system offset'
complete -c mkdiskimage -s z -d 'Use a ZIP-disk geometry.  This needs heads=64 and sect=32'

