# muffin
# Autogenerated from man page /usr/share/man/man1/muffin.1.gz
complete -c muffin -l display -d 'Connect to X display DISPLAY'
complete -c muffin -l replace -d 'a window manager which is running is replaced by MUFFIN'
complete -c muffin -l sm-client-id -d 'Specify a session management ID'
complete -c muffin -l sm-disable -d 'Disable the session management'
complete -c muffin -l sm-save-file -d 'Load a session from FILENAME'
complete -c muffin -l version -d 'Print the version number'
complete -c muffin -s '?' -l help -d 'Show summary of options'

