# nawk
# Autogenerated from man page /usr/share/man/man1/nawk.1.gz
complete -c nawk -l include -d 'options), and values to be made available in the ARGC and ARGV pre-defined AW…'
complete -c nawk -l profile -d 'option, it starts gathering profiling statistics from the execution of the pr…'
complete -c nawk -l debug -d 'option to the command line'
complete -c nawk -s f -d and
complete -c nawk -l file -d 'Read the AWKprogram-file , instead of from the first command line argument'
complete -c nawk -s F
complete -c nawk -l field-separator -d 'Use fs for the input field separator (the value of the FS predefined variable)'
complete -c nawk -s v
complete -c nawk -l assign -d 'Assign the value val to the variable var , before execution of the program be…'
complete -c nawk -s b
complete -c nawk -l characters-as-bytes -d 'Treat all input data as single-byte characters'
complete -c nawk -l posix -d 'option overrides this one'
complete -c nawk -s c
complete -c nawk -l traditional -d 'Run in compatibility mode'
complete -c nawk -s C
complete -c nawk -l copyright -d 'Print the short version of the GNUthe standard output and exit successfully'
complete -c nawk -s d
complete -c nawk -l dump-variables -d 'Print a sorted list of global variables, their types and final values to file '
complete -c nawk -s D
complete -c nawk -s e
complete -c nawk -l source -d 'Use program-text as AWKThis option allows the easy intermixing of library fun…'
complete -c nawk -s E
complete -c nawk -l exec -d 'Similar to'
complete -c nawk -s g
complete -c nawk -l gen-pot -d 'Scan and parse the AWK'
complete -c nawk -s h
complete -c nawk -l help -d 'Print a relatively short summary of the available options on the standard out…'
complete -c nawk -s i
complete -c nawk -s l
complete -c nawk -l load -d 'Load a gawk extension from the shared library lib '
complete -c nawk -s L
complete -c nawk -l lint -d 'Provide warnings about constructs that are dubious or non-portable to other A…'
complete -c nawk -s M
complete -c nawk -l bignum -d 'Force arbitrary precision arithmetic on numbers'
complete -c nawk -s n
complete -c nawk -l non-decimal-data -d 'Recognize octal and hexadecimal values in input data'
complete -c nawk -s N
complete -c nawk -l use-lc-numeric -d 'Force gawk to use the locale\'s decimal point character when parsing input data'
complete -c nawk -s W
complete -c nawk -l nostalgia -d 'Provide a moment of nostalgia for long time awk users'
complete -c nawk -s o
complete -c nawk -l pretty-print -d 'Output a pretty printed version of the program to file '
complete -c nawk -l no-optimize
complete -c nawk -s O
complete -c nawk -l optimize -d 'Enable gawk \'s default optimizations upon the internal representation of the …'
complete -c nawk -s p
complete -c nawk -s P
complete -c nawk -s r
complete -c nawk -l re-interval -d 'Enable the use of interval expressions in regular expression matching (see Re…'
complete -c nawk -s s
complete -c nawk -s S
complete -c nawk -l sandbox -d 'Run gawk in sandbox mode, disabling the system() function, input redirection …'
complete -c nawk -s t
complete -c nawk -l lint-old -d 'Provide warnings about constructs that are not portable to the original versi…'
complete -c nawk -s V
complete -c nawk -l version -d 'Print version information for this particular copy of gawk on the standard ou…'
complete -c nawk -s 1
complete -c nawk -s Y
complete -c nawk -l parsedebug -d 'Turn on yacc (1) or bison (1) debugging output during program parsing'

