# pix
# Autogenerated from man page /usr/share/man/man1/pix.1.gz
complete -c pix -s f -l fullscreen -d 'Start in fullscreen mode'
complete -c pix -s s -l slideshow -d 'Automatically start a slideshow'
complete -c pix -l import-photos -d 'Automatically import digital camera photos'
complete -c pix -l help -d 'Output help information and exit'
complete -c pix -l version -d 'Output version information and exit'

