# pm-hibernate
# Autogenerated from man page /usr/share/man/man8/pm-hibernate.8.gz
complete -c pm-hibernate -l quirk-dpms-on -d 'This option forces the video hardware to turn on the screen during resume'
complete -c pm-hibernate -l quirk-dpms-suspend -d 'This option forces the video hardware to turn off the screen when suspending'
complete -c pm-hibernate -l quirk-radeon-off -d 'This option forces Radeon hardware to turn off the display during suspend and…'
complete -c pm-hibernate -l quirk-s3-bios -d 'This option calls the video BIOS during S3 resume'
complete -c pm-hibernate -l quirk-s3-mode -d 'This option initializes the video card into a VGA text mode, and then uses th…'
complete -c pm-hibernate -l quirk-vbe-post -d 'This option will attempt to reinitialize the video card when resuming from su…'
complete -c pm-hibernate -l quirk-vbemode-restore -d 'This option will save and restore the current VESA mode which may be necessar…'
complete -c pm-hibernate -l quirk-vbestate-restore -d 'This option saves and restores some low level hardware state which may be inv…'
complete -c pm-hibernate -l quirk-vga-mode-3 -d 'This option will try to force the video card into a standard text mode on res…'
complete -c pm-hibernate -l quirk-save-pci -d 'Save the PCI config space for the VGA card'
complete -c pm-hibernate -l store-quirks-as-lkw -d 'Save the quirks the video adaptor required by pm-suspend or pm-suspend-hybrid…'

