# pm-is-supported
# Autogenerated from man page /usr/share/man/man1/pm-is-supported.1.gz
complete -c pm-is-supported -l suspend -d 'Test whether suspend is supported'
complete -c pm-is-supported -l hibernate -d 'Test whether hibernate is supported'
complete -c pm-is-supported -l suspend-hybrid -d 'Test whether hybrid-suspend is supported'

