# redshift-gtk
# Autogenerated from man page /usr/share/man/man1/redshift-gtk.1.gz
complete -c redshift-gtk -s h -d 'Display help message'
complete -c redshift-gtk -s v -d 'Enable verbose output'
complete -c redshift-gtk -s V -d 'Show program version'
complete -c redshift-gtk -s b -d 'Screen brightness to apply (between 0. 1 and 1. 0)'
complete -c redshift-gtk -s c -d 'Load settings from specified configuration file'
complete -c redshift-gtk -s g -d 'Additional gamma correction to apply'
complete -c redshift-gtk -s l -d 'Your current location, in degrees, given as floating point numbers, towards n…'
complete -c redshift-gtk -s m -d 'Method to use to set color temperature (Use "-m list" to see available method…'
complete -c redshift-gtk -s o -d 'One-shot mode (do not continuously adjust color temperature)'
complete -c redshift-gtk -s O -d 'One-shot manual mode (set color temperature)'
complete -c redshift-gtk -s p -d 'Print mode (only print parameters and exit)'
complete -c redshift-gtk -s P -d 'Reset existing gamma ramps before applying new color effect'
complete -c redshift-gtk -s x -d 'Reset mode (remove adjustment from screen)'
complete -c redshift-gtk -s r -d 'Disable fading between color temperatures'
complete -c redshift-gtk -s t -d 'Color temperature to set at daytime/night'

