# snap-hmm
# Autogenerated from man page /usr/share/man/man1/snap-hmm.1.gz
complete -c snap-hmm -o help -d 'report useful information'
complete -c snap-hmm -o lcmask -d 'treat lowercase as N'
complete -c snap-hmm -o plus -d 'predict on plus strand only'
complete -c snap-hmm -o minus -d 'predict on minus strand only'
complete -c snap-hmm -o gff -d 'output annotation as GFF'
complete -c snap-hmm -o ace -d 'output annotation as ACED'
complete -c snap-hmm -o quiet -d 'do not send progress to STDERR'
complete -c snap-hmm -o aa -d 'create FASTA file of proteins'
complete -c snap-hmm -o tx -d 'create FASTA file of transcripts'
complete -c snap-hmm -o xdef -d 'external definitions'
complete -c snap-hmm -o name -d 'name for the gene [default snap]'

