# su-to-root
# Autogenerated from man page /usr/share/man/man1/su-to-root.1.gz
complete -c su-to-root -s c -d 'The command to execute as a string.  This option is mandatory'
complete -c su-to-root -s p -d 'The name of the user to change to, instead of root'
complete -c su-to-root -s X -d 'The command is a X11 program that does not require a terminal'

