# synaptic
# Autogenerated from man page /usr/share/man/man8/synaptic.8.gz
complete -c synaptic -s f -l filter-file -d 'specify an alternative filter settings file'
complete -c synaptic -s i -l initial-filter -d 'apply the filter with number int at startup'
complete -c synaptic -s o -l option -d 'set an internal option (experts only)'

