# unshield
# Autogenerated from man page /usr/share/man/man1/unshield.1.gz
complete -c unshield -s c -d 'Only list/extract this component'
complete -c unshield -s d -d 'Extract files to DIRECTORY'
complete -c unshield -s D -d 'Set debug log level 0 - No logging (default) 1 - Errors only 2 - Errors and w…'
complete -c unshield -s g -d 'Only list/extract this file group'
complete -c unshield -s h -d 'Show help message'
complete -c unshield -s j -d 'Junk paths (do not make directories)'
complete -c unshield -s L -d 'Make file and directory names lowercase'
complete -c unshield -s n -d 'Never overwrite files'
complete -c unshield -s o -d 'Always overwrite files'
complete -c unshield -s O -d 'Use old compression'
complete -c unshield -s r -d 'Save raw data (do not decompress)'
complete -c unshield -s R -d 'Don\'t do any conversion to file and directory names when extracting'
complete -c unshield -s v -d 'Be verbose'
complete -c unshield -s V -d 'Print version information . SS "Commands:"'

