# untex
# Autogenerated from man page /usr/share/man/man1/untex.1.gz
complete -c untex -s o -d 'remove options to LaTeX commands, i.  e'
complete -c untex -s i -d 'process "\\\\include{file}" and "\\\\input{file}" and "\\\\input file" commands'
complete -c untex -s m -d '(try to) remove all math code'
complete -c untex -s u -d 'replace all \\\\"a (etc. ) with ibm (CP850) characters'
complete -c untex -o uiso -d 'replace all \\\\"a (etc. ) with ISO characters'
complete -c untex -o uascii -d 'replace all \\\\"a (etc. ) with ascii characters'
complete -c untex -s g -d 'replace all "a (etc. , from german. sty) with ibm (CP850) characters'
complete -c untex -o giso -d 'replace all "a (etc. , from german. sty) with ISO characters'
complete -c untex -o gascii -d 'replace all "a (etc. , from german. sty) with ascii characters'
complete -c untex -s e -d 'remove environment names'
complete -c untex -s a -d 'remove arguments of commands (not recommended)'

