# update-java-alternatives
# Autogenerated from man page /usr/share/man/man8/update-java-alternatives.8.gz
complete -c update-java-alternatives -s l -l list -d 'List all installed packages (or just <jname>) providing information to set a …'
complete -c update-java-alternatives -s a -l auto -d 'Switch all alternatives of registered jre/sdk installations to automatic mode'
complete -c update-java-alternatives -s s -l set -d 'Set all alternatives of the registered jre/sdk installation to the program pa…'
complete -c update-java-alternatives -l jre -d 'Limit the actions to alternatives belong to a runtime environment, not a deve…'
complete -c update-java-alternatives -l jre-headless -d 'Limit the actions to alternatives belong to the headless part of a runtime en…'
complete -c update-java-alternatives -l plugin -d 'Limit the actions to alternatives providing browser plugins'
complete -c update-java-alternatives -s h -l help -d 'Display a help message'
complete -c update-java-alternatives -s v -l verbose -d 'Verbose output'

