# update-menus
# Autogenerated from man page /usr/share/man/man1/update-menus.1.gz
complete -c update-menus -s v -d 'Verbose output.  Shows all arguments to the /etc/menu-methods programs'
complete -c update-menus -s d -d 'Debug output.  Generates loads of unintelligible output'
complete -c update-menus -s h -l help -d 'Display usage help and exit'
complete -c update-menus -l menufilesdir -d 'Adds directory <dir> to the list of directories to search for menu files in'
complete -c update-menus -l menumethod -d 'Process only the menu method <method> instead of all the menu methods found'
complete -c update-menus -l nodefaultdirs -d 'Disables the search of menu entries in system menu directories'
complete -c update-menus -l nodpkgcheck -d 'Do not discard menu entries for packages that are not installed according to …'
complete -c update-menus -l remove -d 'Remove the menus by calling the menu-methods with --remove'
complete -c update-menus -l stdout -d 'Output the menu list in a format suitable as input for install-menu or a menu…'
complete -c update-menus -l version -d 'Output version information and exit'

