# vdev_id
# Autogenerated from man page /usr/share/man/man8/vdev_id.8.gz
complete -c vdev_id -s d -d 'The device node to classify, like /dev/sda'
complete -c vdev_id -s c -d 'Specifies the path to an alternate configuration file'
complete -c vdev_id -s g -d 'Identifies a physical topology that governs how physical paths are mapped to …'
complete -c vdev_id -s m -d 'Only handle dm-multipath devices'
complete -c vdev_id -s p -d 'Specifies the number of PHY devices associated with a SAS HBA port or SAS swi…'
complete -c vdev_id -s h -d 'Print a usage summary.  El SEE ALSO vdev_id. conf 5'

