# xreader
# Autogenerated from man page /usr/share/man/man1/xreader.1.gz
complete -c xreader -s p -l page-label -d 'Here you can specify a page label, this page will be selected in the document…'
complete -c xreader -s i -l page-index -d 'Here you can specify a page number, this page will be selected in the documen…'
complete -c xreader -s f -l fullscreen -d 'Start xreader in fullscreen mode'
complete -c xreader -s s -l presentation -d 'Start xreader in presentation mode'
complete -c xreader -s w -l preview -d 'Start xreader in preview mode'
complete -c xreader -l display -d 'X display to use'
complete -c xreader -l version -d 'Output version information and exit'
complete -c xreader -s '?' -s h -l help -d 'Print standard command line options'

