# zed
# Autogenerated from man page /usr/share/man/man8/zed.8.gz
complete -c zed -s h -d 'Display a summary of the command-line options'
complete -c zed -s L -d 'Display license information'
complete -c zed -s V -d 'Display version information'
complete -c zed -s v -d 'Be verbose'
complete -c zed -s f -d 'Force the daemon to run if at all possible, disabling security checks and thr…'
complete -c zed -s F -d 'Don\'t daemonise: remain attached to the controlling terminal, log to the stan…'
complete -c zed -s M -d 'Lock all current and future pages in the virtual memory address space'
complete -c zed -s I -d 'Request that the daemon idle rather than exit when the kernel modules are not…'
complete -c zed -s Z -d 'Zero the daemon\'s state, thereby allowing zevents still within the kernel to …'
complete -c zed -s d -d 'Read the enabled ZEDLETs from the specified directory'
complete -c zed -s p -d 'Write the daemon\'s process ID to the specified file'
complete -c zed -s P -d 'Custom $PATH for zedlets to use'
complete -c zed -s s -d 'Write the daemon\'s state to the specified file'
complete -c zed -s j -d 'Allow at most jobs ZEDLETs to run concurrently, delaying execution of new one…'

