# zgenhostid
# Autogenerated from man page /usr/share/man/man8/zgenhostid.8.gz
complete -c zgenhostid -s h -d 'Display a summary of the command-line options'
complete -c zgenhostid -s f -d 'Allow output overwrite'
complete -c zgenhostid -s o -d 'Write to filename instead of the default /etc/hostid'

