# zhack
# Autogenerated from man page /usr/share/man/man1/zhack.1.gz
complete -c zhack -s c -d 'Read pool configuration from the cachefile, which is /etc/zfs/zpool'
complete -c zhack -s d -d 'Search for pool members in dir.  Can be specified more than once'

