# zoe-loop
# Autogenerated from man page /usr/share/man/man1/zoe-loop.1.gz
complete -c zoe-loop -o all
complete -c zoe-loop -o Vec -o IVec -o FVec -o TVec -o Hash -o Xtree
complete -c zoe-loop -o Feature -o FeatureVec
complete -c zoe-loop -o FastaFile -o DNA -o Protein -o Alignment -o CDS -o Palign
complete -c zoe-loop -o Distribution -o Duration -o State -o Transition
complete -c zoe-loop -o FeatureTable
complete -c zoe-loop -o Model -o Scanner -o Counter
complete -c zoe-loop -o HMM

