local function add_icons(theme)
    local icon_dir                                  = os.getenv("HOME") .. "/.config/awesome/themes/icons/white/icons"

    theme.menu_submenu_icon                         = icon_dir .. "/submenu.png"
    theme.awesome_icon                              = icon_dir .. "/awesome.png"
    theme.taglist_squares_sel                       = icon_dir .. "/square_sel.png"
    theme.taglist_squares_unsel                     = icon_dir .. "/square_unsel.png"
    theme.layout_tile                               = icon_dir .. "/tile.png"
    theme.layout_tileleft                           = icon_dir .. "/tileleft.png"
    theme.layout_tilebottom                         = icon_dir .. "/tilebottom.png"
    theme.layout_tiletop                            = icon_dir .. "/tiletop.png"
    theme.layout_fairv                              = icon_dir .. "/fairv.png"
    theme.layout_fairh                              = icon_dir .. "/fairh.png"
    theme.layout_spiral                             = icon_dir .. "/spiral.png"
    theme.layout_dwindle                            = icon_dir .. "/dwindle.png"
    theme.layout_max                                = icon_dir .. "/max.png"
    theme.layout_fullscreen                         = icon_dir .. "/fullscreen.png"
    theme.layout_magnifier                          = icon_dir .. "/magnifier.png"
    theme.layout_floating                           = icon_dir .. "/floating.png"
    theme.widget_cal                                = icon_dir .. "/cal.png"
    theme.widget_battery_full                       = icon_dir .. "/battery_full.png"
    theme.widget_battery_low                        = icon_dir .. "/battery_low.png"
    theme.widget_battery_high                       = icon_dir .. "/battery_high.png"
    theme.widget_battery_empty                      = icon_dir .. "/battery_empty.png"
    theme.widget_battery_charging                   = icon_dir .. "/battery_charging.png"
    theme.widget_mem                                = icon_dir .. "/mem.png"
    theme.widget_cpu                                = icon_dir .. "/cpu.png"
    theme.widget_temp                               = icon_dir .. "/temp.png"
    theme.widget_net                                = icon_dir .. "/net.png"
    theme.widget_hdd                                = icon_dir .. "/hdd.png"
    theme.widget_music                              = icon_dir .. "/note.png"
    theme.widget_music_on                           = icon_dir .. "/note.png"
    theme.widget_music_pause                        = icon_dir .. "/pause.png"
    theme.widget_music_stop                         = icon_dir .. "/stop.png"
    theme.widget_vol_loud                           = icon_dir .. "/vol_loud.png"
    theme.widget_vol_medium                         = icon_dir .. "/vol_medium.png"
    theme.widget_vol_low                            = icon_dir .. "/vol_low.png"
    theme.widget_vol_mute                           = icon_dir .. "/vol_mute.png"
    theme.widget_mail                               = icon_dir .. "/mail.png"
    theme.widget_mail_on                            = icon_dir .. "/mail_on.png"
    theme.widget_task                               = icon_dir .. "/task.png"
    theme.widget_scissors                           = icon_dir .. "/scissors.png"
    theme.widget_weather                            = icon_dir .. "/dish.png"
    theme.titlebar_close_button_focus               = icon_dir .. "/titlebar/close_focus.png"
    theme.titlebar_close_button_normal              = icon_dir .. "/titlebar/close_normal.png"
    theme.titlebar_ontop_button_focus_active        = icon_dir .. "/titlebar/ontop_focus_active.png"
    theme.titlebar_ontop_button_normal_active       = icon_dir .. "/titlebar/ontop_normal_active.png"
    theme.titlebar_ontop_button_focus_inactive      = icon_dir .. "/titlebar/ontop_focus_inactive.png"
    theme.titlebar_ontop_button_normal_inactive     = icon_dir .. "/titlebar/ontop_normal_inactive.png"
    theme.titlebar_minimize_button_focus_active     = icon_dir .. "/titlebar/sticky_focus_active.png"
    theme.titlebar_minimize_button_normal_active    = icon_dir .. "/titlebar/sticky_normal_active.png"
    theme.titlebar_minimize_button_focus_inactive   = icon_dir .. "/titlebar/sticky_focus_inactive.png"
    theme.titlebar_minimize_button_normal_inactive  = icon_dir .. "/titlebar/sticky_normal_inactive.png"
    theme.titlebar_floating_button_focus_active     = icon_dir .. "/titlebar/floating_focus_active.png"
    theme.titlebar_floating_button_normal_active    = icon_dir .. "/titlebar/floating_normal_active.png"
    theme.titlebar_floating_button_focus_inactive   = icon_dir .. "/titlebar/floating_focus_inactive.png"
    theme.titlebar_floating_button_normal_inactive  = icon_dir .. "/titlebar/floating_normal_inactive.png"
    theme.titlebar_maximized_button_focus_active    = icon_dir .. "/titlebar/maximized_focus_active.png"
    theme.titlebar_maximized_button_normal_active   = icon_dir .. "/titlebar/maximized_normal_active.png"
    theme.titlebar_maximized_button_focus_inactive  = icon_dir .. "/titlebar/maximized_focus_inactive.png"
    theme.titlebar_maximized_button_normal_inactive = icon_dir .. "/titlebar/maximized_normal_inactive.png"
    return theme
end

return add_icons